#r "nuget: Microsoft.Extensions.Http"
#r "nuget: Microsoft.Extensions.Hosting"
#r "nuget: Microsoft.AspNetCore.Components.WebAssembly"
#r "nuget: Microsoft.Extensions.DependencyInjection"
#r "nuget: Microsoft.DeepDev.TokenizerLib"
#r "nuget: Azure.Search.Documents"
#r "nuget: Microsoft.SemanticKernel"
#r "nuget: FSharp.SystemTextJson"
#r "nuget: FSharp.Data"
#r "nuget: FSharp.Collections.ParallelSeq"
#r "nuget: FSharp.Control.AsyncSeq"
#r "nuget: FsPickler.Json"
#r "nuget: Docnet.Core"
#r "nuget: PdfPig, *-*"
#r "nuget: DocumentFormat.OpenXml"
//#r "nuget: Bolero"
//#r "nuget: MudBlazor"
//#r "nuget: Plotly.NET"
#r "nuget: Azure.Identity"
#r "nuget: azure.security.keyvault.secrets"
#r "nuget: FSharp.CosmosDb"
#r "nuget: ExcelDataReader"
#r "nuget: ExcelDataReader.DataSet"
#r "nuget: FSharp.Compiler.Service"
#r "nuget: System.Text.Encoding.CodePages"
//#r "nuget: FSharp.Core, 8.0.400"


#I "../../FsOpenAI.Shared"
#load "Constants.fs"
#load "Utils.fs"
#load "AppConfig.fs"
#load "Settings.fs"
#load "Types.fs"
#load "Interactions.Core.fs"
#load "Interactions.fs"


#I "../../FsOpenAI.GenAI"
#load "AsyncExts.fs"
#load "Env.fs"
#load "Connection.fs"
#load "Monitoring.fs"
#load "Sessions.fs"
#load "Gen/GenUtils.fs"
#load "Gen/Prompts.fs"
#load "Gen/Indexes.fs"
#load "Gen/SemanticVectorSearch.fs"
#load "Gen/Completions.fs"
#load "Gen/WebCompletion.fs"
#load "Gen/IndexQnA.fs"
#load "Gen/Vision/VisionApi.fs"
//#load "Gen/Vision/Image.fs"
#load "Gen/DocQnA.fs"
