
// This file was generated by the createTypes.fsx script. Do not edit this file directly.
namespace rec FsOpenAI.TravelSurvey.Types
open System


type DataSets = {
    Households   : Household list // List of Household records
    Vehicles     : Vehicle list //List of Vehicle records for each Household
    Persons      : Person list //List of Household members
    Trips        : Trip list //One record per Household member's travel day trip (If at least one trip is made) 
    LongTrips    : LongTrip list //Long trip taken by Household members
}

type Household = {
    /// Unique Identifier- Household
    HOUSEID : string 
    /// 7-day natl household weight
    WTHHFIN : float 
    /// 5-day natl household weight
    WTHHFIN5D : float 
    /// 2-day natl household weight
    WTHHFIN2D : float 
    /// Count of adult household members at least 18 years old
    NUMADLT : float 
    /// Whether home owned or rented
    HOMEOWN : HOMEOWN 
    /// Type of home
    HOMETYPE : HOMETYPE 
    /// MSA heavy rail status for household
    RAIL : YesNo 
    /// Census division classification for home address
    CENSUS_D : CENSUS_D 
    /// Census region classification for home address
    CENSUS_R : CENSUS_R 
    /// Hispanic status of household respondent
    HH_HISP : YesNo 
    /// Number of drivers in the household
    DRVRCNT : float 
    /// Count of household trips on travel day
    CNTTDHH : float 
    /// Grouping of household by combination of Census division, MSA status, and presence of rail
    CDIVMSAR : CDIVMSAR 
    /// All HH members completed survey?
    FLAG100 : YesNo 
    /// Household income
    HHFAMINC : HHFAMINC 
    /// Household income (imputed)
    HHFAMINC_IMP : HHFAMINC_IMP 
    /// Race of household respondent
    HH_RACE : HH_RACE 
    /// Total number of people in household
    HHSIZE : float 
    /// Total number of vehicles in household
    HHVEHCNT : float 
    /// Flag indicating at least 2 persons in HH are related
    HHRELATD : YesNo 
    /// Life Cycle classification for the household
    LIF_CYC : LIF_CYC 
    /// MSA category for the HH home address
    MSACAT : MSACAT 
    /// Population size category of the MSA from the five-year ACS API
    MSASIZE : MSASIZE 
    /// Travel day - day of week
    TRAVDAY : TRAVDAY 
    /// Household urban area classification, based on 2020 TIGER/Line Shapefile
    URBAN : URBAN 
    /// Urban area size where home address is located
    URBANSIZE : URBANSIZE 
    /// Household in urban/rural area
    URBRUR : YesNo 
    /// Count of household members 5-17 years old
    PPT517 : float 
    /// Count of household members under 5 years old
    YOUNGCHILD : float 
    /// Count of responding persons in household
    RESP_CNT : float 
    /// Household in urban/rural area based on 2010 Census
    URBRUR_2010 : YesNo 
    /// Date of travel day (YYYYMM)
    TDAYDATE : DateTime 
    /// Count of workers in household
    WRKCOUNT : float 
    /// Household Stratum ID
    STRATUMID : string 
}

type Vehicle = {
    /// Unique Identifier- Household
    HOUSEID : string 
    /// Vehicle ID within household
    VEHID : string 
    /// Vehicle year
    VEHYEAR : float 
    /// Vehicle make ID
    MAKE : MAKE 
    /// Total number of vehicles in household
    HHVEHCNT : float 
    /// Vehicle type
    VEHTYPE : VEHTYPE 
    /// Type of fuel vehicle runs on
    VEHFUEL : VEHFUEL 
    /// Vehicle used for business purposes
    VEHCOMMERCIAL : YesNo 
    /// Vehicle used for rideshare
    VEHCOM_RS : YesNo 
    /// Vehicle used for delivery service
    VEHCOM_DEL : YesNo 
    /// Vehicle used for other business purposes
    VEHCOM_OTH : YesNo 
    /// Over past 30 days, how many days was vehicle used for business purposes?
    COMMERCIALFREQ : Response 
    /// Over past 30 days, how many days was vehicle used for rideshare?
    HHVEHUSETIME_RS : Response 
    /// Over past 30 days, how many days was vehicle used for deliveries?
    HHVEHUSETIME_DEL : Response 
    /// Over past 30 days, how many days was vehicle used for other business?
    HHVEHUSETIME_OTH : Response 
    /// Vehicle owned for 1 year or more
    VEHOWNED : YesNo 
    /// Main driver of vehicle
    WHOMAIN : WHOMAIN 
    /// Unique vehicle identifier
    VEHCASEID : string 
    /// Self-reported annualized mile estimate
    ANNMILES : Response 
    /// Hybrid vehicle
    HYBRID : YesNo 
    /// Age of vehicle, based on model year
    VEHAGE : float 
    /// Vehicles owned less than 1 year - months owned
    VEHOWNMO : Response 
    /// Count of adult household members at least 18 years old
    NUMADLT : float 
    /// Whether home owned or rented
    HOMEOWN : HOMEOWN 
    /// MSA heavy rail status for household
    RAIL : YesNo 
    /// Census division classification for home address
    CENSUS_D : CENSUS_D 
    /// Census region classification for home address
    CENSUS_R : CENSUS_R 
    /// Hispanic status of household respondent
    HH_HISP : YesNo 
    /// Number of drivers in the household
    DRVRCNT : float 
    /// Grouping of household by combination of Census division, MSA status, and presence of rail
    CDIVMSAR : CDIVMSAR 
    /// Household income
    HHFAMINC : HHFAMINC 
    /// Race of household respondent
    HH_RACE : HH_RACE 
    /// Total number of people in household
    HHSIZE : float 
    /// Life Cycle classification for the household
    LIF_CYC : LIF_CYC 
    /// MSA category for the HH home address
    MSACAT : MSACAT 
    /// Population size category of the MSA from the five-year ACS API
    MSASIZE : MSASIZE 
    /// Travel day - day of week
    TRAVDAY : TRAVDAY 
    /// Household urban area classification, based on 2020 TIGER/Line Shapefile
    URBAN : URBAN 
    /// Urban area size where home address is located
    URBANSIZE : URBANSIZE 
    /// Household in urban/rural area
    URBRUR : YesNo 
    /// Date of travel day (YYYYMM)
    TDAYDATE : DateTime 
    /// Count of workers in household
    WRKCOUNT : float 
    /// Household Stratum ID
    STRATUMID : string 
    /// 7-day natl household weight
    WTHHFIN : float 
    /// 5-day natl household weight
    WTHHFIN5D : float 
    /// 2-day natl household weight
    WTHHFIN2D : float 
    /// Household income (imputed)
    HHFAMINC_IMP : HHFAMINC_IMP 
}

type Person = {
    /// Unique Identifier- Household
    HOUSEID : string 
    /// Person ID within household
    PERSONID : string 
    /// 7 day National person weight
    WTPERFIN : float 
    /// 5 day National person weight
    WTPERFIN5D : float 
    /// 2 day National person weight
    WTPERFIN2D : float 
    /// Respondent age
    R_AGE : float 
    /// Respondent sex
    R_SEX : R_SEX 
    /// Respondent relationship to primary respondent
    R_RELAT : R_RELAT 
    /// Employment status of respondent
    WORKER : WORKER 
    /// Driver status, derived
    DRIVER : YesNo 
    /// Respondent race
    R_RACE : R_RACE 
    /// Great circle distance (miles) between home and work
    GCDWORK : Response 
    /// Away from home entire travel day
    OUTOFTWN : YesNo 
    /// Public Transit Usage on Travel Date
    USEPUBTR : YesNo 
    /// Respondent race (imputed)
    R_RACE_IMP : HH_RACE 
    /// Person 5 or older - Hispanic or Latino
    R_HISP : YesNo 
    /// Survey completed by self or someone else
    PROXY : YesNo 
    /// Who is completing the survey
    WHOPROXY : WHOPROXY 
    /// Highest level of education
    EDUC : EDUC 
    /// Used taxi service in last 30 days
    LAST30_TAXI : YesNo 
    /// Used rideshare in last 30 days
    LAST30_RDSHR : YesNo 
    /// Used e-scooters in last 30 days
    LAST30_ESCT : YesNo 
    /// Used public transit in last 30 days
    LAST30_PT : YesNo 
    /// Used motorcycle in last 30 days
    LAST30_MTRC : YesNo 
    /// Walked from place to place in last 30 days
    LAST30_WALK : YesNo 
    /// Used bicycle in last 30 days
    LAST30_BIKE : YesNo 
    /// Used bike share in last 30 days
    LAST30_BKSHR : LAST30_BKSHR 
    /// Days in last 30 days taxi service used
    TAXISERVICE : Response 
    /// Days in last 30 days rideshare used
    RIDESHARE22 : Response 
    /// Days in last 30 days e-scooter used
    ESCOOTERUSED : Response 
    /// Days in last 30 days public transit used
    PTUSED : Response 
    /// Discounted transit pass used in past 30 days
    TRNPASS : YesNo 
    /// Days in last 30 days motorcycle used
    MCTRANSIT : Response 
    /// Days in last 30 days walking used
    WALKTRANSIT : Response 
    /// Days in last 30 days cycling used
    BIKETRANSIT : Response 
    /// Days in last 30 days bike share used
    BIKESHARE22 : Response 
    /// Fewer trips in past 30 days
    USAGE1 : USAGE1 
    /// Reason fewer trips - more deliveries
    USAGE2_1 : USAGE2_1 
    /// Reason fewer trips - did not feel safe
    USAGE2_2 : USAGE2_2 
    /// Reason fewer trips - did not feel clean/healthy
    USAGE2_3 : USAGE2_3 
    /// Reason fewer trips - not reliable
    USAGE2_4 : USAGE2_4 
    /// Reason fewer trips - did not go where needed
    USAGE2_5 : USAGE2_5 
    /// Reason fewer trips - unaffordable
    USAGE2_6 : USAGE2_6 
    /// Reason fewer trips - health problems
    USAGE2_7 : USAGE2_7 
    /// Reason fewer trips - no time
    USAGE2_8 : USAGE2_8 
    /// Reason fewer trips - other
    USAGE2_9 : USAGE2_9 
    /// Reason fewer trips - COVID 19
    USAGE2_10 : USAGE2_10 
    /// Language other than English spoken at home
    QACSLAN1 : YesNo 
    /// How well this person speaks English
    QACSLAN3 : QACSLAN3 
    /// Worked for pay last week
    PAYPROF : YesNo 
    /// Primary activity for those who did not work for pay last week
    PRMACT : PRMACT 
    /// Hours worked for pay each week
    EMPLOYMENT2 : Response 
    /// Drive for work
    DRIVINGOCCUPATION : YesNo 
    /// Vehicle driven for work
    DRIVINGVEHICLE : DRIVINGVEHICLE 
    /// Description of work location
    WRKLOC : WRKLOC 
    /// Days per week worked from home
    WKFMHM22 : WKFMHM22 
    /// Usual transport to work
    WRKTRANS : WRKTRANS 
    /// Employer pays for discounted transit pass
    EMPPASS : YesNo 
    /// Enrolled in school or academic program
    SCHOOL1 : YesNo 
    /// School or academic program description
    STUDE : STUDE 
    /// Type of K-12 school enrolled in
    SCHTYP : SCHTYP 
    /// Type of non K-12 school enrolled in
    SCHOOL1C : SCHOOL1C 
    /// Usual transport to school
    SCHTRN1 : SCHTRN1 
    /// Number of online purchase deliveries in past 30 days
    DELIVER : Response 
    /// Number of times goods delivered in past 30 days
    DELIV_GOOD : Response 
    /// Number of times food delivered in past 30 days
    DELIV_FOOD : Response 
    /// Number of times groceries delivered in past 30 days
    DELIV_GROC : Response 
    /// Number of times services delivered in the past 30 days
    DELIV_PERS : Response 
    /// Number of times returned online purchase by home pickup
    RET_HOME : Response 
    /// Number of times returned online purchase to post office/UPS/Fed Ex/ similar
    RET_PUF : Response 
    /// Number of times returned online purchase at Amazon dropoff center
    RET_AMZ : Response 
    /// Number of times returned online purchase by direct to store
    RET_STORE : Response 
    /// Condition or disability that makes travel difficult
    MEDCOND : MEDCOND 
    /// Length of time respondent has had condition
    MEDCOND6 : MEDCOND6 
    /// Uses cane or walking stick
    W_CANE : W_CANE 
    /// Uses walker or crutches
    W_WKCR : W_CANE 
    /// Uses devices to aid the blind or visually impaired
    W_VISIMP : W_CANE 
    /// Uses motorized scooter or wheelchair
    W_SCCH : W_CANE 
    /// Uses manual scooter or wheel chair
    W_CHAIR : W_CANE 
    /// Uses no medical device for mobility
    W_NONE : W_CANE 
    /// Reduced travel due to condition or disability
    CONDTRAV : CONDNIGH 
    /// Asked others for rides due to condition or disability
    CONDRIDE : CONDNIGH 
    /// Limited driving to daytime due to condition or disability
    CONDNIGH : CONDNIGH 
    /// Given up driving due to condition or disability
    CONDRIVE : CONDNIGH 
    /// Used bus or subway less frequently due to condition or disability
    CONDPUB : CONDNIGH 
    /// Used special transportation services due to condition or disability
    CONDSPEC : CONDNIGH 
    /// Used rideshare due to condition or disability
    CONDSHARE : CONDNIGH 
    /// Travel not affected by condition or disability
    CONDNONE : CONDNIGH 
    /// Prefer not to answer if travel is affected by condition or disability
    CONDRF : CONDNIGH 
    /// Started travel day at home
    FRSTHM : YesNo 
    /// Paid for parking at any time during travel day
    PARK : YesNo 
    /// Pay for home parking
    PARKHOME : YesNo 
    /// Whether respondent pays to park at home
    PARKHOMEAMT : PARKHOMEAMT 
    /// Cost of parking at home
    PARKHOMEAMT_PAMOUNT : Response 
    /// Duration of payment
    PARKHOMEAMT_PAYTYPE : PARKHOMEAMT_PAYTYPE 
    /// Reason for not taking trips on travel day
    SAMEPLC : SAMEPLC 
    /// COVID impact on travel to a physical work location
    COV1_WK : COV1_SCH 
    /// COVID impact on travel to a physical school/class location
    COV1_SCH : COV1_SCH 
    /// COVID impact on use of public transit
    COV1_PT : COV1_OHD 
    /// COVID impact on online purchases for home delivery
    COV1_OHD : COV1_OHD 
    /// Work travel changes temporary or permanent
    COV2_WK : COV2_OHD 
    /// School travel changes temporary or permanent
    COV2_SCH : COV2_SCH 
    /// Public transit use changes temporary or permanent
    COV2_PT : COV2_OHD 
    /// Home delivery changes temporary or permanent
    COV2_OHD : COV2_OHD 
    /// Count of person trips on travel day
    CNTTDTR : float 
    /// Respondent sex (imputed)
    R_SEX_IMP : YesNo 
    /// Count of adult household members at least 18 years old
    NUMADLT : float 
    /// Whether home owned or rented
    HOMEOWN : HOMEOWN 
    /// MSA heavy rail status for household
    RAIL : YesNo 
    /// Census division classification for home address
    CENSUS_D : CENSUS_D 
    /// Census region classification for home address
    CENSUS_R : CENSUS_R 
    /// Hispanic status of household respondent
    HH_HISP : YesNo 
    /// Number of drivers in the household
    DRVRCNT : float 
    /// Grouping of household by combination of Census division, MSA status, and presence of rail
    CDIVMSAR : CDIVMSAR 
    /// Household income
    HHFAMINC : HHFAMINC 
    /// Race of household respondent
    HH_RACE : HH_RACE 
    /// Total number of people in household
    HHSIZE : float 
    /// Total number of vehicles in household
    HHVEHCNT : float 
    /// Life Cycle classification for the household
    LIF_CYC : LIF_CYC 
    /// MSA category for the HH home address
    MSACAT : MSACAT 
    /// Population size category of the MSA from the five-year ACS API
    MSASIZE : MSASIZE 
    /// Travel day - day of week
    TRAVDAY : TRAVDAY 
    /// Household urban area classification, based on 2020 TIGER/Line Shapefile
    URBAN : URBAN 
    /// Urban area size where home address is located
    URBANSIZE : URBANSIZE 
    /// Household in urban/rural area
    URBRUR : YesNo 
    /// Date of travel day (YYYYMM)
    TDAYDATE : DateTime 
    /// Count of workers in household
    WRKCOUNT : float 
    /// Household Stratum ID
    STRATUMID : string 
    /// Household income (imputed)
    HHFAMINC_IMP : HHFAMINC_IMP 
}

type Trip = {
    /// Unique Identifier- Household
    HOUSEID : string 
    /// Person ID within household
    PERSONID : string 
    /// Trip ID for each trip a person took
    TRIPID : string 
    /// Renumbered sequential tripid
    SEQ_TRIPID : string 
    /// Unique vehicle identifier
    VEHCASEID : string 
    /// Started travel day at home
    FRSTHM : YesNo 
    /// Paid for parking at any time during travel day
    PARK : YesNo 
    /// Household member drove on trip
    HHMEMDRV : HHMEMDRV 
    /// Weekend trip
    TDWKND : YesNo 
    /// Travel day - day of week
    TRAVDAY : TRAVDAY 
    /// Trip origin and destination at Identical location
    LOOP_TRIP : YesNo 
    /// Time at Destination (minutes)
    DWELTIME : Response 
    /// Used public transit on trip
    PUBTRANS : YesNo 
    /// General purpose of trip
    TRIPPURP : TRIPPURP 
    /// Reason for previous trip
    WHYFROM : WHYFROM 
    /// Trip purpose summary
    WHYTRP1S : WHYTRP1S 
    /// Trip Duration in Minutes
    TRVLCMIN : Response 
    /// 24 hour local start time of trip
    STRTTIME : Response 
    /// 24 hour local end time of trip
    ENDTIME : Response 
    /// Household vehicle used for trip
    TRPHHVEH : TRPHHVEH 
    /// Vehicle ID within household
    VEHID : string 
    /// Trip mode, derived
    TRPTRANS : TRPTRANS 
    /// Number of people on trip
    NUMONTRP : float 
    /// Person 1 was on trip
    ONTD_P1 : YesNo 
    /// Person 2 was on trip
    ONTD_P2 : ONTD_P2 
    /// Person 3 was on trip
    ONTD_P3 : ONTD_P2 
    /// Person 4 was on trip
    ONTD_P4 : ONTD_P2 
    /// Person 5 was on trip
    ONTD_P5 : ONTD_P2 
    /// Person 6 was on trip
    ONTD_P6 : ONTD_P2 
    /// Person 7 was on trip
    ONTD_P7 : ONTD_P2 
    /// Person 8 was on trip
    ONTD_P8 : ONTD_P2 
    /// Person 9 was on trip
    ONTD_P9 : ONTD_P2 
    /// Person 10 was on trip
    ONTD_P10 : ONTD_P10 
    /// Number of non-household members on trip
    NONHHCNT : float 
    /// Number of household members on trip
    HHACCCNT : float 
    /// Person who drove on trip
    WHODROVE : WHODROVE 
    /// Flag for driver on trip
    DRVR_FLG : DRVR_FLG 
    /// Flag for passenger on trip
    PSGR_FLG : PSGR_FLG 
    /// Imputed person who drove on trip
    WHODROVE_IMP : WHODROVE 
    /// Amount paid for parking
    PARK2_PAMOUNT : Response 
    /// Periodicity of parking payment
    PARK2_PAYTYPE : PARK2_PAYTYPE 
    /// Paid for parking on this trip
    PARK2 : PARK2 
    /// Reason for travel to destination
    WHYTO : WHYTO 
    /// Minutes walked from parking to destination
    WALK : WALK 
    /// Calculated Trip distance converted into miles
    TRPMILES : Response 
    /// 7 day National trip weight
    WTTRDFIN : float 
    /// 5 day National trip weight
    WTTRDFIN5D : float 
    /// 2 day National trip weight
    WTTRDFIN2D : float 
    /// Unique identifier for every trip record in the file
    TDCASEID : string 
    /// Calculated Trip distance (miles) for Driver Trips
    VMT_MILE : Response 
    /// Weekly regional gasoline price, in cents, during the week of the household's travel day
    GASPRICE : float 
    /// Travel day trip purpose consistent with 1990 NPTS design
    WHYTRP90 : WHYTRP90 
    /// Count of adult household members at least 18 years old
    NUMADLT : float 
    /// Whether home owned or rented
    HOMEOWN : HOMEOWN 
    /// MSA heavy rail status for household
    RAIL : YesNo 
    /// Census division classification for home address
    CENSUS_D : CENSUS_D 
    /// Census region classification for home address
    CENSUS_R : CENSUS_R 
    /// Hispanic status of household respondent
    HH_HISP : YesNo 
    /// Number of drivers in the household
    DRVRCNT : float 
    /// Grouping of household by combination of Census division, MSA status, and presence of rail
    CDIVMSAR : CDIVMSAR 
    /// Household income
    HHFAMINC : HHFAMINC 
    /// Race of household respondent
    HH_RACE : HH_RACE 
    /// Total number of people in household
    HHSIZE : float 
    /// Total number of vehicles in household
    HHVEHCNT : float 
    /// Life Cycle classification for the household
    LIF_CYC : LIF_CYC 
    /// MSA category for the HH home address
    MSACAT : MSACAT 
    /// Population size category of the MSA from the five-year ACS API
    MSASIZE : MSASIZE 
    /// Household urban area classification, based on 2020 TIGER/Line Shapefile
    URBAN : URBAN 
    /// Urban area size where home address is located
    URBANSIZE : URBANSIZE 
    /// Household in urban/rural area
    URBRUR : YesNo 
    /// Date of travel day (YYYYMM)
    TDAYDATE : DateTime 
    /// Count of workers in household
    WRKCOUNT : float 
    /// Household Stratum ID
    STRATUMID : string 
    /// Respondent age
    R_AGE : float 
    /// Respondent sex
    R_SEX : R_SEX 
    /// Employment status of respondent
    WORKER : WORKER 
    /// Driver status, derived
    DRIVER : YesNo 
    /// Respondent race
    R_RACE : R_RACE 
    /// Person 5 or older - Hispanic or Latino
    R_HISP : YesNo 
    /// Survey completed by self or someone else
    PROXY : YesNo 
    /// Highest level of education
    EDUC : EDUC 
    /// Primary activity for those who did not work for pay last week
    PRMACT : PRMACT 
    /// Respondent sex (imputed)
    R_SEX_IMP : YesNo 
    /// Vehicle type
    VEHTYPE : VEHTYPE 
    /// Household income (imputed)
    HHFAMINC_IMP : HHFAMINC_IMP 
}

type LongTrip = {
    /// Unique Identifier- Household
    HOUSEID : string 
    /// Person ID within household
    PERSONID : string 
    /// Number of long distance trips in past 30 days
    LONGDIST : float 
    /// Mode of travel for last long distance trip
    MAINMODE : MAINMODE 
    /// Farthest destination on the trip was in the US or outside US
    INT_FLAG : INT_FLAG 
    /// Number of people with respondent on long distance trip
    LD_NUMONTRP : Response 
    /// Person 1 on long distance trip
    ONTP_P1 : ONTP_P 
    /// Person 2 on long distance trip
    ONTP_P2 : ONTP_P 
    /// Person 3 on long distance trip
    ONTP_P3 : ONTP_P 
    /// Person 4 on long distance trip
    ONTP_P4 : ONTP_P 
    /// Person 5 on long distance trip
    ONTP_P5 : ONTP_P 
    /// Person 6 on long distance trip
    ONTP_P6 : ONTP_P 
    /// Person 7 on long distance trip
    ONTP_P7 : ONTP_P 
    /// Person 8 on long distance trip
    ONTP_P8 : ONTP_P 
    /// Person 9 on long distance trip
    ONTP_P9 : ONTP_P 
    /// Person 10 on long distance trip
    ONTP_P10 : ONTP_P 
    /// Main reason for most recent long distance trip
    FARREAS : FARREAS 
    /// Number of times used AMTRAK in past year
    LD_AMT : float 
    /// Number of times used Intra-City bus in past year
    LD_ICB : float 
    /// Source of long distance data
    LDT_FLAG : LDT_FLAG 
    /// Beginning date of trip (YYYYMM)
    BEGTRIP : Response 
    /// Ending date of trip (YYYYMM)
    ENDTRIP : Response 
    /// Nights away on long distance trip
    NTSAWAY : Response 
    /// Trip includes weekend
    WEEKEND : WEEKEND 
    /// Date of most recent long distance trip (YYYYMM)
    MRT_DATE : Response 
    /// Farthest domestic destination Census division code (domestic trips only)
    FARCDIV : EXITCDIV 
    /// Farthest domestic destination Census region FIPS code (domestic trips only)
    FARCREG : FARCREG 
    /// Great circle distance from home to farthest domestic dest (domestic trips only)
    GCDTOT : Response 
    /// Domestic airport hub size based on FY23 NPIAS hub type status (international trips only)
    AIRSIZE : AIRSIZE 
    /// Census division at which respondent exited the US
    EXITCDIV : EXITCDIV 
    /// Flag for long distance trips of 50 miles or more
    GCD_FLAG : GCD_FLAG 
    /// Count of adult household members at least 18 years old
    NUMADLT : float 
    /// Whether home owned or rented
    HOMEOWN : HOMEOWN 
    /// MSA heavy rail status for household
    RAIL : YesNo 
    /// Census division classification for home address
    CENSUS_D : CENSUS_D 
    /// Census region classification for home address
    CENSUS_R : CENSUS_R 
    /// Hispanic status of household respondent
    HH_HISP : YesNo 
    /// Number of drivers in the household
    DRVRCNT : float 
    /// Grouping of household by combination of Census division, MSA status, and presence of rail
    CDIVMSAR : CDIVMSAR 
    /// Household income
    HHFAMINC : HHFAMINC 
    /// Household income (imputed)
    HHFAMINC_IMP : HHFAMINC_IMP 
    /// Race of household respondent
    HH_RACE : HH_RACE 
    /// Total number of people in household
    HHSIZE : float 
    /// Total number of vehicles in household
    HHVEHCNT : float 
    /// Life Cycle classification for the household
    LIF_CYC : LIF_CYC 
    /// MSA category for the HH home address
    MSACAT : MSACAT 
    /// Population size category of the MSA from the five-year ACS API
    MSASIZE : MSASIZE 
    /// Travel day - day of week
    TRAVDAY : TRAVDAY 
    /// Household urban area classification, based on 2020 TIGER/Line Shapefile
    URBAN : URBAN 
    /// Urban area size where home address is located
    URBANSIZE : URBANSIZE 
    /// Household in urban/rural area
    URBRUR : YesNo 
    /// Date of travel day (YYYYMM)
    TDAYDATE : DateTime 
    /// Count of workers in household
    WRKCOUNT : float 
    /// Household Stratum ID
    STRATUMID : string 
    /// 7 day National person weight
    WTPERFIN : float 
    /// 5 day National person weight
    WTPERFIN5D : float 
    /// 2 day National person weight
    WTPERFIN2D : float 
    /// Respondent age
    R_AGE : float 
    /// Respondent sex
    R_SEX : R_SEX 
    /// Employment status of respondent
    WORKER : WORKER 
    /// Driver status, derived
    DRIVER : YesNo 
    /// Respondent race
    R_RACE : R_RACE 
    /// Person 5 or older - Hispanic or Latino
    R_HISP : YesNo 
    /// Survey completed by self or someone else
    PROXY : YesNo 
    /// Highest level of education
    EDUC : EDUC 
    /// Respondent sex (imputed)
    R_SEX_IMP : YesNo 
}


/// Vehicle type
type VEHTYPE =
| ``VEHTYPE_Valid skip``
| ``VEHTYPE_Automobile|Car|Stationwagon``
| ``VEHTYPE_Van (Minivan|Cargo|Passenger)``
| ``VEHTYPE_SUV (Santa Fe, Tahoe, Jeep, etc)``
| ``VEHTYPE_Pickup Truck``
| ``VEHTYPE_Other Truck``
| ``VEHTYPE_Recreational vehicle (RV)|Motorhome``
| VEHTYPE_MotorcycleMoped
| ``VEHTYPE_Something else``

type Response = 
    | R_NotAscertained
    | R_Skipped
    | Value of float

/// Length of time respondent has had condition
type MEDCOND6 =
| ``MEDCOND6_Valid skip``
| ``MEDCOND6_I prefer not to answer``
| ``MEDCOND6_Don't know``
| ``MEDCOND6_Not ascertained``
| ``MEDCOND6_6 months or less``
| ``MEDCOND6_More than 6 months``
| ``MEDCOND6_Entire life``

/// Reason for not taking trips on travel day
type SAMEPLC =
| ``SAMEPLC_Valid skip``
| ``SAMEPLC_I prefer not to answer``
| ``SAMEPLC_Don't know``
| ``SAMEPLC_Not ascertained``
| ``SAMEPLC_Personally sick or quarantining``
| ``SAMEPLC_Vacation or personal day``
| SAMEPLC_Caretaking
| ``SAMEPLC_Disabled or home-bound``
| ``SAMEPLC_Worked at home (for pay)``
| ``SAMEPLC_Not scheduled to work``
| ``SAMEPLC_Household chores|projects``
| ``SAMEPLC_Bad weather``
| ``SAMEPLC_Out of country``
| ``SAMEPLC_No transportation available``
| ``SAMEPLC_School holiday|teacher workday``
| ``SAMEPLC_Hospitalized or otherwise confined``
| ``SAMEPLC_School from home``
| ``SAMEPLC_Reluctant to travel``
| ``SAMEPLC_Something else, please specify``

/// Uses cane or walking stick
type W_CANE =
| ``W_CANE_Valid skip``
| ``W_CANE_I prefer not to answer``
| ``W_CANE_Don't know``
| ``W_CANE_Not ascertained``
| W_CANE_Selected
| ``W_CANE_Not Selected``

/// COVID impact on travel to a physical school/class location
type COV1_SCH =
| ``COV1_SCH_Valid skip``
| ``COV1_SCH_Don't Know``
| ``COV1_SCH_Not ascertained``
| ``COV1_SCH_Do more often than before``
| ``COV1_SCH_Do the same as before``
| ``COV1_SCH_Do less often than before``
| ``COV1_SCH_Not Applicable``

/// Home delivery changes temporary or permanent
type COV2_OHD =
| ``COV2_OHD_Valid skip``
| ``COV2_OHD_Don't Know``
| ``COV2_OHD_Not ascertained``
| COV2_OHD_Temporary
| COV2_OHD_Permanent

/// Used bike share in last 30 days
type LAST30_BKSHR =
| ``LAST30_BKSHR_Valid skip``
| ``LAST30_BKSHR_Don't Know``
| ``LAST30_BKSHR_Not ascertained``
| LAST30_BKSHR_Yes
| LAST30_BKSHR_No

/// School travel changes temporary or permanent
type COV2_SCH =
| ``COV2_SCH_Valid skip``
| ``COV2_SCH_Don't Know``
| COV2_SCH_Temporary
| COV2_SCH_Permanent

type YesNo = 
    | YN_NotAscertained
    | YN_Skipped
    | ``YN_Don't Know``
    | Yes
    | No

/// Minutes walked from parking to destination
type WALK =
| ``WALK_Valid skip``
| ``WALK_Not ascertained``
| ``WALK_0 minutes| parked in the same building``
| ``WALK_1 to less than 5 minutes``
| ``WALK_5 to less than 10 minutes``
| ``WALK_10 to less than 15 minutes``
| ``WALK_15 to less than 20 minutes``
| ``WALK_20 minutes or more``
| ``WALK_N|A - someone else took vehicle``
| ``WALK_N|A - Didn't park``

/// Reason fewer trips - other
type USAGE2_9 =
| ``USAGE2_9_Valid skip``
| ``USAGE2_9_Not ascertained``
| ``USAGE2_9_Another reason``
| ``USAGE2_9_Not Selected``

/// Reason fewer trips - did not go where needed
type USAGE2_5 =
| ``USAGE2_5_Valid skip``
| ``USAGE2_5_Not ascertained``
| ``USAGE2_5_Available transportation did not go where I need to go``
| ``USAGE2_5_Not Selected``

/// Main reason for most recent long distance trip
type FARREAS =
| ``FARREAS_Valid skip``
| ``FARREAS_Not ascertained``
| ``FARREAS_Business trip``
| ``FARREAS_Personal vacation``
| ``FARREAS_Visit family or friends``
| ``FARREAS_Other, specify``

/// Mode of travel for last long distance trip
type MAINMODE =
| ``MAINMODE_Valid skip``
| ``MAINMODE_Not ascertained``
| MAINMODE_Car
| MAINMODE_Van
| ``MAINMODE_SUV|Crossover``
| ``MAINMODE_Pickup truck``
| ``MAINMODE_Recreational Vehicle``
| MAINMODE_Motorcycle
| ``MAINMODE_Public or commuter bus``
| ``MAINMODE_School bus``
| ``MAINMODE_Subway or elevated rail``
| ``MAINMODE_Commuter rail``
| MAINMODE_Amtrak
| MAINMODE_Airplane
| ``MAINMODE_Taxicab or limo service``
| ``MAINMODE_Other ride-sharing service``
| ``MAINMODE_Paratransit| Dial a ride``
| ``MAINMODE_Bicycle (including bikeshare, ebike, etc)``
| MAINMODE_Walked
| ``MAINMODE_Other (specify)``
| MAINMODE_Ferryboat
| ``MAINMODE_Charter|tour buses``
| ``MAINMODE_Inter-city bus service``

/// Reason fewer trips - COVID 19
type USAGE2_10 =
| ``USAGE2_10_Valid skip``
| ``USAGE2_10_Not ascertained``
| ``USAGE2_10_Concerns related to COVID 19``
| ``USAGE2_10_Not Selected``

/// Reason fewer trips - no time
type USAGE2_8 =
| ``USAGE2_8_Valid skip``
| ``USAGE2_8_Not ascertained``
| ``USAGE2_8_Did not have time to travel``
| ``USAGE2_8_Not Selected``

/// Flag for long distance trips of 50 miles or more
type GCD_FLAG =
| ``GCD_FLAG_Valid Skip``
| ``GCD_FLAG_Not Ascertained``
| ``GCD_FLAG_GCD 50 miles or more``
| ``GCD_FLAG_GCD less than 50 miles``

/// Reason fewer trips - health problems
type USAGE2_7 =
| ``USAGE2_7_valid skip``
| ``USAGE2_7_Not ascertained``
| ``USAGE2_7_Had health problems and unable to travel``
| ``USAGE2_7_Not Selected``

/// Household member drove on trip
type HHMEMDRV =
| ``HHMEMDRV_Valid skip``
| ``HHMEMDRV_Not ascertained``
| ``HHMEMDRV_Household member drove``
| ``HHMEMDRV_Non-household member drove``

/// Reason fewer trips - more deliveries
type USAGE2_1 =
| ``USAGE2_1_Valid skip``
| ``USAGE2_1_Not ascertained``
| ``USAGE2_1_I had more home deliveries``
| ``USAGE2_1_Not Selected``

/// Type of non K-12 school enrolled in
type SCHOOL1C =
| ``SCHOOL1C_Valid skip``
| ``SCHOOL1C_Not ascertained``
| ``SCHOOL1C_In- person``
| SCHOOL1C_Online
| ``SCHOOL1C_Other (specify)``

/// Farthest destination on the trip was in the US or outside US
type INT_FLAG =
| ``INT_FLAG_valid skip``
| ``INT_FLAG_not ascertained``
| ``INT_FLAG_Inside the US``
| ``INT_FLAG_Outside the US``

/// School or academic program description
type STUDE =
| ``STUDE_Valid skip``
| ``STUDE_Not ascertained``
| ``STUDE_K-12th grade including GED``
| ``STUDE_Vocation|Technical|Trade School``
| ``STUDE_Part-time college or university``
| ``STUDE_Full-time college or university``
| ``STUDE_Other (specify)``

/// Census division at which respondent exited the US
type EXITCDIV =
| ``EXITCDIV_Valid Skip``
| ``EXITCDIV_Not Ascertained``
| ``EXITCDIV_New England``
| ``EXITCDIV_Middle Atlantic``
| ``EXITCDIV_East North Central``
| ``EXITCDIV_West North Central``
| ``EXITCDIV_South Atlantic``
| ``EXITCDIV_East South Central``
| ``EXITCDIV_West South Central``
| EXITCDIV_Mountain
| EXITCDIV_Pacific

/// Domestic airport hub size based on FY23 NPIAS hub type status (international trips only)
type AIRSIZE =
| ``AIRSIZE_Valid Skip``
| ``AIRSIZE_Not Ascertained``
| AIRSIZE_Nonhub
| AIRSIZE_Small
| AIRSIZE_Medium
| AIRSIZE_Large

/// Farthest domestic destination Census region FIPS code (domestic trips only)
type FARCREG =
| ``FARCREG_Valid Skip``
| ``FARCREG_Not Ascertained``
| FARCREG_Northeast
| FARCREG_Midwest
| FARCREG_South
| FARCREG_West

/// Person 1 on long distance trip
type ONTP_P =
| ``ONTP_P_Valid skip``
| ``ONTP_P_Not ascertained``
| ``ONTP_P_On trip``
| ``ONTP_P_Not on trip``

/// Person who drove on trip
type WHODROVE =
| ``WHODROVE_Valid skip``
| ``WHODROVE_Not ascertained``
| ``WHODROVE_Person 1``
| ``WHODROVE_Person 2``
| ``WHODROVE_Person 3``
| ``WHODROVE_Person 4``
| ``WHODROVE_Person 5``
| ``WHODROVE_Person 7``
| ``WHODROVE_Non household member drove``

/// Type of K-12 school enrolled in
type SCHTYP =
| ``SCHTYP_Valid skip``
| ``SCHTYP_Not ascertained``
| ``SCHTYP_Public or private school``
| ``SCHTYP_Home schooled``
| ``SCHTYP_Other (specify)``

/// Limited driving to daytime due to condition or disability
type CONDNIGH =
| ``CONDNIGH_Valid skip``
| ``CONDNIGH_Not ascertained``
| CONDNIGH_Selected
| ``CONDNIGH_Not Selected``

/// Trip includes weekend
type WEEKEND =
| ``WEEKEND_Valid Skip``
| ``WEEKEND_Not Ascertained``
| ``WEEKEND_Short weekend (2 or 3 days and includes a FRI and|or SAT) and return date not FRI``
| ``WEEKEND_Long weekend (4 to 6 days and includes a FRI and|or SAT) and return date not FRI``
| ``WEEKEND_Not weekend trip (all other trips)``

/// Reason fewer trips - did not feel clean/healthy
type USAGE2_3 =
| ``USAGE2_3_Valid skip``
| ``USAGE2_3_Not ascertained``
| ``USAGE2_3_Transportation did not feel clean or healthy``
| ``USAGE2_3_Not Selected``

/// Reason fewer trips - did not feel safe
type USAGE2_2 =
| ``USAGE2_2_Valid skip``
| ``USAGE2_2_Not ascertained``
| ``USAGE2_2_Transportation did not feel safe``
| ``USAGE2_2_Not Selected``

/// Reason fewer trips - not reliable
type USAGE2_4 =
| ``USAGE2_4_Valid skip``
| ``USAGE2_4_Not ascertained``
| ``USAGE2_4_Transportation was not reliable``
| ``USAGE2_4_Not Selected``

/// Reason fewer trips - unaffordable
type USAGE2_6 =
| ``USAGE2_6_valid skip``
| ``USAGE2_6_Not ascertained``
| ``USAGE2_6_Unable to afford available forms of transportation``
| ``USAGE2_6_Not Selected``

/// How well this person speaks English
type QACSLAN3 =
| ``QACSLAN3_Valid skip``
| ``QACSLAN3_Not ascertained``
| ``QACSLAN3_Very well``
| QACSLAN3_Well
| ``QACSLAN3_Not well``
| ``QACSLAN3_Not at all``

/// Fewer trips in past 30 days
type USAGE1 =
| ``USAGE1_Valid skip``
| ``USAGE1_Not ascertained``
| ``USAGE1_Yes, took fewer trips``
| ``USAGE1_No, did not take fewer trips``

/// Paid for parking on this trip
type PARK2 =
| ``PARK2_Valid skip``
| ``PARK2_Paid to park``
| ``PARK2_N|A Paid for by employer``
| ``PARK2_N|A Paid for by school``
| ``PARK2_Paid but I don't remember the cost``
| ``PARK2_I did not pay for parking at this location``

/// Whether respondent pays to park at home
type PARKHOMEAMT =
| ``PARKHOMEAMT_Valid skip``
| ``PARKHOMEAMT_Paid to park at home``
| ``PARKHOMEAMT_Paid but I don't remember the cost``

/// Usual transport to work
type WRKTRANS =
| ``WRKTRANS_Valid skip``
| WRKTRANS_Car
| WRKTRANS_Van
| ``WRKTRANS_SUV|Crossover``
| ``WRKTRANS_Pickup truck``
| WRKTRANS_Motorcycle
| ``WRKTRANS_Public or commuter bus``
| ``WRKTRANS_School bus``
| ``WRKTRANS_Streetcar or trolley car``
| ``WRKTRANS_Subway or elevated rail``
| ``WRKTRANS_Commuter rail``
| WRKTRANS_Amtrak
| WRKTRANS_Airplane
| ``WRKTRANS_Taxicab or limo service``
| ``WRKTRANS_Other ride-sharing service``
| ``WRKTRANS_Paratransit| Dial a ride``
| ``WRKTRANS_Bicycle (including bikeshare, ebike, etc)``
| ``WRKTRANS_E-scooter``
| WRKTRANS_Walked
| ``WRKTRANS_Other (specify)``
| WRKTRANS_Ferryboat

/// Usual transport to school
type SCHTRN1 =
| ``SCHTRN1_Valid skip``
| SCHTRN1_Car
| SCHTRN1_Van
| ``SCHTRN1_SUV|Crossover``
| ``SCHTRN1_Pickup truck``
| SCHTRN1_Motorcycle
| ``SCHTRN1_Public or commuter bus``
| ``SCHTRN1_School bus``
| ``SCHTRN1_Streetcar or trolley car``
| ``SCHTRN1_Subway or elevated rail``
| ``SCHTRN1_Commuter rail``
| ``SCHTRN1_Taxicab or limo service``
| ``SCHTRN1_Other ride-sharing service``
| ``SCHTRN1_Paratransit| Dial a ride``
| ``SCHTRN1_Bicycle (including bikeshare, ebike, etc)``
| ``SCHTRN1_E-scooter``
| SCHTRN1_Walked
| ``SCHTRN1_Other (specify)``

/// Flag for driver on trip
type DRVR_FLG =
| ``DRVR_FLG_Valid skip``
| ``DRVR_FLG_Driver on trip``
| ``DRVR_FLG_Not driver on trip``

/// Highest level of education
type EDUC =
| ``EDUC_Valid skip``
| ``EDUC_Less than high school``
| ``EDUC_Some high school, no diploma|GED``
| ``EDUC_High school graduate, have diploma|GED``
| ``EDUC_Some college, no degree| some trade school``
| ``EDUC_Associates degree (2-year)| trade school certificate``
| ``EDUC_Bachelor's degree``
| ``EDUC_Master's degree``
| ``EDUC_Professional|Doctorate degree``

/// Days per week worked from home
type WKFMHM22 =
| ``WKFMHM22_Valid skip``
| WKFMHM22_Never
| ``WKFMHM22_One or two days a week``
| ``WKFMHM22_Three or four days a week``
| ``WKFMHM22_Five or more days a week| Entire work week``

/// Periodicity of parking payment
type PARK2_PAYTYPE =
| ``PARK2_PAYTYPE_Valid skip``
| ``PARK2_PAYTYPE_One Time``
| ``PARK2_PAYTYPE_Per Week``
| ``PARK2_PAYTYPE_Per Month``
| ``PARK2_PAYTYPE_Per Semester``
| ``PARK2_PAYTYPE_Per Year``

/// Duration of payment
type PARKHOMEAMT_PAYTYPE =
| ``PARKHOMEAMT_PAYTYPE_Valid skip``
| ``PARKHOMEAMT_PAYTYPE_One Time``
| ``PARKHOMEAMT_PAYTYPE_Per Month``

/// Description of work location
type WRKLOC =
| ``WRKLOC_Valid skip``
| ``WRKLOC_Only one work location outside of home``
| ``WRKLOC_Work location regularly varies (different offices|job sites)``
| ``WRKLOC_Only work at home (telework, self-employed)``
| ``WRKLOC_Drive|travel for work (driver, sales)``

/// Flag for passenger on trip
type PSGR_FLG =
| ``PSGR_FLG_Valid skip``
| ``PSGR_FLG_Passenger on trip``
| ``PSGR_FLG_Not passenger on trip``

/// Who is completing the survey
type WHOPROXY =
| ``WHOPROXY_Valid skip``
| WHOPROXY_Person1
| ``WHOPROXY_Person 2``
| ``WHOPROXY_Person 3``
| ``WHOPROXY_Person 4``
| ``WHOPROXY_Person 5``
| ``WHOPROXY_Person 6``
| ``WHOPROXY_Someone else``

/// Person 2 was on trip
type ONTD_P2 =
| ``ONTD_P2_Valid skip``
| ONTD_P2_Selected
| ``ONTD_P2_Not Selected``

/// Primary activity for those who did not work for pay last week
type PRMACT =
| ``PRMACT_Valid skip``
| ``PRMACT_Temporarily absent from a job or business``
| ``PRMACT_Looking for work|unemployed``
| ``PRMACT_A homemaker``
| ``PRMACT_Going to school``
| PRMACT_Retired
| ``PRMACT_Something else``

/// Employment status of respondent
type WORKER =
| ``WORKER_Valid skip``
| WORKER_Worker
| ``WORKER_Not worker``

/// Vehicle driven for work
type DRIVINGVEHICLE =
| ``DRIVINGVEHICLE_Valid skip``
| ``DRIVINGVEHICLE_Yes, use a household vehicle``
| ``DRIVINGVEHICLE_No, use non-household vehicle``
| ``DRIVINGVEHICLE_Use both household and non-household vehicle``

/// Household vehicle used for trip
type TRPHHVEH =
| ``TRPHHVEH_Valid skip``
| ``TRPHHVEH_Yes, used a household vehicle``
| ``TRPHHVEH_No, did not use a household vehicle``

/// Person 10 was on trip
type ONTD_P10 =
| ``ONTD_P10_Valid skip``
| ``ONTD_P10_Not Selected``

/// Condition or disability that makes travel difficult
type MEDCOND =
| ``MEDCOND_I prefer not to answer``
| ``MEDCOND_Don't know``
| ``MEDCOND_Not ascertained``
| MEDCOND_Yes
| MEDCOND_No

/// Household income
type HHFAMINC =
| ``HHFAMINC_I prefer not to answer``
| ``HHFAMINC_I don't know``
| ``HHFAMINC_Less than 10,000``
| ``HHFAMINC_10,000 to 14,999``
| ``HHFAMINC_15,000 to 24,999``
| ``HHFAMINC_25,000 to 34,999``
| ``HHFAMINC_35,000 to 49,999``
| ``HHFAMINC_50,000 to 74,999``
| ``HHFAMINC_75,000 to 99,999``
| ``HHFAMINC_100,000 to 124,999``
| ``HHFAMINC_125,000 to 149,999``
| ``HHFAMINC_150,000 to 199,999``
| ``HHFAMINC_200,000 or more``

/// Respondent sex
type R_SEX =
| R_SEX_Refuse
| ``R_SEX_Don't know``
| ``R_SEX_Not ascertained``
| R_SEX_Male
| R_SEX_Female

/// COVID impact on online purchases for home delivery
type COV1_OHD =
| ``COV1_OHD_Don't Know``
| ``COV1_OHD_Not ascertained``
| ``COV1_OHD_Do more often than before``
| ``COV1_OHD_Do the same as before``
| ``COV1_OHD_Do less often than before``
| ``COV1_OHD_Not Applicable``

/// Type of fuel vehicle runs on
type VEHFUEL =
| ``VEHFUEL_Not ascertained``
| VEHFUEL_Gas
| VEHFUEL_Diesel
| VEHFUEL_Biodiesel
| ``VEHFUEL_Plug-in hybrid``
| ``VEHFUEL_Electric only``
| ``VEHFUEL_Hybrid, gas|electric, non plug-in``
| ``VEHFUEL_Uses other fuel``

/// General purpose of trip
type TRIPPURP =
| ``TRIPPURP_Not ascertained``
| ``TRIPPURP_Home-based work (HBW)``
| ``TRIPPURP_Home-based shopping (HBSHP)``
| ``TRIPPURP_Home-based social|recreational (HBSOC)``
| ``TRIPPURP_Home-based other (HBO)``
| ``TRIPPURP_Not a home-based trip (NHB)``

/// Source of long distance data
type LDT_FLAG =
| ``LDT_FLAG_Not Ascertained``
| ``LDT_FLAG_Long distance info derived from travel day``
| ``LDT_FLAG_Long distance info asked of respondents``
| ``LDT_FLAG_More than 5 years since last long distance trip``
| ``LDT_FLAG_Never taken a trip longer than 50 miles``

/// Main driver of vehicle
type WHOMAIN =
| ``WHOMAIN_Not ascertained``
| WHOMAIN_Person1
| ``WHOMAIN_Person 2``
| ``WHOMAIN_Person 3``
| ``WHOMAIN_Person 4``
| ``WHOMAIN_Person 5``
| ``WHOMAIN_Person 6``
| ``WHOMAIN_Person 7``
| ``WHOMAIN_Person 8``
| ``WHOMAIN_No one``
| ``WHOMAIN_Someone else``

/// Reason for previous trip
type WHYFROM =
| ``WHYFROM_Not ascertained``
| ``WHYFROM_Regular activities at home``
| ``WHYFROM_Work from home (paid)``
| ``WHYFROM_Work at a non-home location``
| ``WHYFROM_Work activity to drop-off|pickup someone|something``
| ``WHYFROM_Other work-related activities``
| ``WHYFROM_Attend school as a student``
| ``WHYFROM_Attend childcare or adult care``
| ``WHYFROM_Volunteer activities (not paid)``
| ``WHYFROM_Change type of transportation``
| ``WHYFROM_Drop off|pick up someone (personal)``
| ``WHYFROM_Health care visit``
| ``WHYFROM_Buy meals``
| ``WHYFROM_Shop|buy|pick-up or return goods``
| ``WHYFROM_Other family|personal errands``
| ``WHYFROM_Recreational activities``
| WHYFROM_Exercise
| ``WHYFROM_Visit friends or relatives``
| ``WHYFROM_Rest or relaxation|vacation``
| ``WHYFROM_Religious or other community activities``
| ``WHYFROM_Something else (specify)``

/// Respondent relationship to primary respondent
type R_RELAT =
| ``R_RELAT_Not ascertained``
| ``R_RELAT_Spouse|Partner``
| R_RELAT_Child
| R_RELAT_Parent
| ``R_RELAT_Brother|Sister``
| ``R_RELAT_Other relative``
| ``R_RELAT_Not related``
| R_RELAT_Self

/// Respondent race
type R_RACE =
| ``R_RACE_Not ascertained``
| R_RACE_White
| ``R_RACE_Black or African American``
| R_RACE_Asian
| ``R_RACE_American Indian|Alaska Native``
| ``R_RACE_Native Hawaiian|Pacific Islander``
| ``R_RACE_Multiple races selected``
| ``R_RACE_Other race``

/// Vehicle make ID
type MAKE =
| ``MAKE_Suppressed for confidential reason``
| MAKE_Jeep
| MAKE_Chrysler
| MAKE_Dodge
| MAKE_Ford
| MAKE_Lincoln
| ``MAKE_Buick | Opel``
| MAKE_Cadillac
| MAKE_Chevrolet
| MAKE_Pontiac
| MAKE_GMC
| ``MAKE_Other Domestic Manufacturers (eg, Tesla)``
| MAKE_Volkswagen
| MAKE_Audi
| MAKE_BMW
| ``MAKE_Nissan|Datsun``
| MAKE_Honda
| MAKE_Mazda
| ``MAKE_Mercedes-Benz``
| MAKE_Subaru
| MAKE_Toyota
| MAKE_Volvo
| MAKE_Mitsubishi
| MAKE_Acura
| MAKE_Hyundai
| MAKE_Infiniti
| MAKE_Lexus
| MAKE_KIA
| ``MAKE_Harley-Davidson``
| ``MAKE_Other Make``

/// Urban area size where home address is located
type URBANSIZE =
| ``URBANSIZE_50,000-199,999``
| ``URBANSIZE_200,000-499,999``
| ``URBANSIZE_500,000-999,999``
| ``URBANSIZE_1,000,000 or more with heavy rail``
| ``URBANSIZE_1,000,000 or more without heavy rail``
| ``URBANSIZE_Not in urbanized area``

/// Trip mode, derived
type TRPTRANS =
| TRPTRANS_Car
| TRPTRANS_Van
| ``TRPTRANS_SUV|Crossover``
| ``TRPTRANS_Pickup truck``
| ``TRPTRANS_Recreational Vehicle``
| TRPTRANS_Motorcycle
| ``TRPTRANS_Public or commuter bus``
| ``TRPTRANS_School bus``
| ``TRPTRANS_Street car or trolley car``
| ``TRPTRANS_Subway or elevated rail``
| ``TRPTRANS_Commuter rail``
| TRPTRANS_Amtrak
| TRPTRANS_Airplane
| ``TRPTRANS_Taxicab or limo service``
| ``TRPTRANS_Other ride-sharing service``
| ``TRPTRANS_Paratransit| Dial a ride``
| ``TRPTRANS_Bicycle (including bikeshare, ebike, etc)``
| ``TRPTRANS_E-scooter``
| TRPTRANS_Walked
| ``TRPTRANS_Other (specify)``

/// Trip purpose summary
type WHYTRP1S =
| WHYTRP1S_Home
| WHYTRP1S_Work
| ``WHYTRP1S_School|Daycare|Religious``
| ``WHYTRP1S_Medical|Dental services``
| ``WHYTRP1S_Shopping|Errands``
| ``WHYTRP1S_Social|Recreational``
| ``WHYTRP1S_Transport someone``
| WHYTRP1S_Meals
| ``WHYTRP1S_Something else``

/// Population size category of the MSA from the five-year ACS API
type MSASIZE =
| ``MSASIZE_In an MSA of Less than 250,000``
| ``MSASIZE_In an MSA of 250,000 - 499,999``
| ``MSASIZE_In an MSA of 500,000 - 999,999``
| ``MSASIZE_In an MSA or CMSA of 1,000,000 - 2,999,999``
| ``MSASIZE_In an MSA or CMSA of 3 million or more``
| ``MSASIZE_Not in MSA or CMSA``

/// Household urban area classification, based on 2020 TIGER/Line Shapefile
type URBAN =
| ``URBAN_In an urban area``
| ``URBAN_In an Urban cluster``
| ``URBAN_In an area surrounded by urban areas``
| ``URBAN_Not in urban area``

/// Household income (imputed)
type HHFAMINC_IMP =
| ``HHFAMINC_IMP_Less than 10,000``
| ``HHFAMINC_IMP_10,000 to 14,999``
| ``HHFAMINC_IMP_15,000 to 24,999``
| ``HHFAMINC_IMP_25,000 to 34,999``
| ``HHFAMINC_IMP_35,000 to 49,999``
| ``HHFAMINC_IMP_50,000 to 74,999``
| ``HHFAMINC_IMP_75,000 to 99,999``
| ``HHFAMINC_IMP_100,000 to 124,999``
| ``HHFAMINC_IMP_125,000 to 149,999``
| ``HHFAMINC_IMP_150,000 to 199,999``
| ``HHFAMINC_IMP_200,000 or more``

/// MSA category for the HH home address
type MSACAT =
| ``MSACAT_MSA of 1 million or more, with rail``
| ``MSACAT_MSA of 1 million or more, without rail``
| ``MSACAT_MSA less than 1 million``
| ``MSACAT_Not in MSA``

/// Census division classification for home address
type CENSUS_D =
| ``CENSUS_D_New England``
| ``CENSUS_D_Middle Atlantic``
| ``CENSUS_D_East North Central``
| ``CENSUS_D_West North Central``
| ``CENSUS_D_South Atlantic``
| ``CENSUS_D_East South Central``
| ``CENSUS_D_West South Central``
| CENSUS_D_Mountain
| CENSUS_D_Pacific

/// Census region classification for home address
type CENSUS_R =
| CENSUS_R_Northeast
| CENSUS_R_Midwest
| CENSUS_R_South
| CENSUS_R_West

/// Life Cycle classification for the household
type LIF_CYC =
| ``LIF_CYC_one adult, no children``
| ``LIF_CYC_2  adults, no children``
| ``LIF_CYC_one adult, youngest child 0-5``
| ``LIF_CYC_2  adults, youngest child 0-5``
| ``LIF_CYC_one adult, youngest child 6-15``
| ``LIF_CYC_2  adults, youngest child 6-15``
| ``LIF_CYC_one adult, youngest child 16-21``
| ``LIF_CYC_2  adults, youngest child 16-21``
| ``LIF_CYC_one adult, retired, no children``
| ``LIF_CYC_2  adults, retired, no children``

/// Type of home
type HOMETYPE =
| ``HOMETYPE_One-family detached``
| ``HOMETYPE_One-family attached (townhome, condo)``
| ``HOMETYPE_Building with 2 or more apartments``
| ``HOMETYPE_Mobile home``
| ``HOMETYPE_Boat, RV, van, etc``

/// Whether home owned or rented
type HOMEOWN =
| ``HOMEOWN_Owned by hh member with mortgage or loan``
| ``HOMEOWN_Owned by hh member free and clear (no mortgage)``
| ``HOMEOWN_Rented by hh member``
| ``HOMEOWN_Occupied without payment``

/// Reason for travel to destination
type WHYTO =
| ``WHYTO_Regular activities at home``
| ``WHYTO_Work from home (paid)``
| ``WHYTO_Work at a non-home location``
| ``WHYTO_Work activity to drop-off|pickup someone|something``
| ``WHYTO_Other work-related activities``
| ``WHYTO_Attend school as a student``
| ``WHYTO_Attend childcare or adult care``
| ``WHYTO_Volunteer activities (not paid)``
| ``WHYTO_Change type of transportation``
| ``WHYTO_Drop off|pick up someone (personal)``
| ``WHYTO_Health care visit``
| ``WHYTO_Buy meals``
| ``WHYTO_Shop|buy|pick-up or return goods``
| ``WHYTO_Other family|personal errands``
| ``WHYTO_Recreational activities``
| WHYTO_Exercise
| ``WHYTO_Visit friends or relatives``
| ``WHYTO_Rest or relaxation|vacation``
| ``WHYTO_Religious or other community activities``
| ``WHYTO_Something else (specify)``

/// Travel day - day of week
type TRAVDAY =
| TRAVDAY_Sunday
| TRAVDAY_Monday
| TRAVDAY_Tuesday
| TRAVDAY_Wednesday
| TRAVDAY_Thursday
| TRAVDAY_Friday
| TRAVDAY_Saturday

/// Travel day trip purpose consistent with 1990 NPTS design
type WHYTRP90 =
| ``WHYTRP90_To|From Work``
| ``WHYTRP90_Work-Related Business``
| WHYTRP90_Shopping
| ``WHYTRP90_Other Family|Personal Business``
| ``WHYTRP90_School|Church``
| ``WHYTRP90_Medical|Dental``
| ``WHYTRP90_Visit Friends|Relatives``
| ``WHYTRP90_Other Social|Recreational``
| WHYTRP90_Other
| ``WHYTRP90_Refused | Don't Know``

/// Race of household respondent
type HH_RACE =
| HH_RACE_White
| ``HH_RACE_Black or African American``
| HH_RACE_Asian
| ``HH_RACE_American Indian|Alaska Native``
| ``HH_RACE_Native Hawaiian|Pacific Islander``
| ``HH_RACE_Multiple races selected``
| ``HH_RACE_Other race``

/// Grouping of household by combination of Census division, MSA status, and presence of rail
type CDIVMSAR =
| ``CDIVMSAR_New England MSA|CMSA of 1 million  with heavy rail``
| ``CDIVMSAR_New England MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_New England MSA of less than 1 million``
| ``CDIVMSAR_New England Not in an MSA``
| ``CDIVMSAR_Mid-Atlantic MSA|CMSA of 1 million  with heavy rail``
| ``CDIVMSAR_Mid-Atlantic MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_Mid-Atlantic MSA of less than 1 million``
| ``CDIVMSAR_Mid-Atlantic Not in an MSA``
| ``CDIVMSAR_East North Central MSA|CMSA of 1 million  with heavy rail``
| ``CDIVMSAR_East North Central MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_East North Central MSA of less than 1 million``
| ``CDIVMSAR_East North Central Not in an MSA``
| ``CDIVMSAR_West North Central MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_West North Central MSA of less than 1 million``
| ``CDIVMSAR_West North Central Not in an MSA``
| ``CDIVMSAR_South Atlantic MSA|CMSA of 1 million  with heavy rail``
| ``CDIVMSAR_South Atlantic MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_South Atlantic MSA of less than 1 million``
| ``CDIVMSAR_South Atlantic Not in an MSA``
| ``CDIVMSAR_East South Central MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_East South Central MSA of less than 1 million``
| ``CDIVMSAR_East South Central Not in an MSA``
| ``CDIVMSAR_West South Central MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_West South Central MSA of less than 1 million``
| ``CDIVMSAR_West South Central Not in an MSA``
| ``CDIVMSAR_Mountain MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_Mountain MSA of less than 1 million``
| ``CDIVMSAR_Mountain Not in an MSA``
| ``CDIVMSAR_Pacific MSA|CMSA of 1 million  with heavy rail``
| ``CDIVMSAR_Pacific MSA|CMSA of 1 million  w|o heavy rail``
| ``CDIVMSAR_Pacific MSA of less than 1 million``
| ``CDIVMSAR_Pacific Not in an MSA``


module Helpers =

    let formatNumber (f:float) : string = sprintf "%0.2f" f

    let formatNumberPercent (f:float) : string = sprintf "%0.2f%%" f
